camera:
  resolution: [640, 480]
  fps: 30
  warmup_time: 2.5

motion:
  delta_threshold: 5
  min_area: 1000
  resize_width: 500

notification:
  min_distance: 60

backup:
  output_path: /tmp

app:
  out_path: /tmp/out.txt
  err_path: /tmp/out.txt
  pidfile_path: /tmp/rpisurv.pid

