camera:
  resolution: [640, 480]
  fps: 30
  warmup_time: 2.5

motion:
  delta_threshold: 18
  min_area: 500
  resize_width: 500

notification:
  min_distance: 60

backup:
  output_path: /tmp

app:
  out_path: /tmp
  pidfile_path: /tmp/rpisurv.pid
  web_path: ../web

alive-notification:
  trigger: interval
  hours: 1

